language: python
sudo: required
services:
  - docker
python:
  - "2.7"
os:
  - linux
before_install:
  - sudo add-apt-repository -y ppa:longsleep/golang-backports
  - sudo apt-get update
  - sudo apt-get -y install golang-go
  - pip install -r tests/requirements.txt
  - docker pull minio/minio
  - docker pull ubuntu
  - docker build -t tes-wait -f tests/docker_files/tes-wait/Dockerfile tests/docker_files/tes-wait/
install:
  - make depends
  - make
script: 
  - make lint
  - make test
notifications:
  email: false
