language: python
sudo: required
services:
  - docker
python:
  - "2.7"
os:
  - linux
before_install:
  - sudo apt-get update
  - sudo apt-get install -y golang
  - pip install -r tests/requirements.txt
  - docker pull minio/minio
  - docker pull ubuntu
  - make gometalinter
install:
  - make depends
  - make
script: 
  - make metalint
  - flake8 .
  - nosetests tests
notifications:
  email: false
