HostName: funnel-server
ContentDir: /opt/funnel/web
Scheduler: gce
Schedulers:
  GCE:
    Project: isb-cgc-04-0029
    Zone: us-west1-b
Storage:
- GS:
  FromEnv: true
Worker:
  ServerAddress: funnel-server:9090
  Metadata:
    gce: yes
  Storage:
  - GS:
    FromEnv: true
