DBPath: /opt/funnel/funnel.db
ContentDir: /opt/funnel/share
WorkDir: /opt/funnel/work-dir
HostName: funnel-server
Scheduler: gce
Schedulers:
  GCE:
    Project: isb-cgc-04-0029
    Zone: us-west1-b
Storage:
- Local:
  AllowedDirs:
    - /opt/funnel/shared-bucket
- GS:
  FromEnv: true
